### ISSUE TITLE
Add --no_sub_dir to configure

### ISSUE THREAD

**Issue by rlfontenot** [EdwardALuke/loci#25]
This issue will add the --no_sub_dir feature to the configure step. The --no_sub_dir feature will disable building ${LOCI_BASE}/Loci-(build info), but instead only use the  --prefix=<install_directory> specified at configure time. The post-appending of the Loci-(build_info) can be problematic for users on HPC systems that use module files, as, for example, Loci/CHEM or Loci/GGFS require ${LOCI_BASE} which is pulled from --prefix+Loci(build_info). Not specifying --no_sub_dir will keep the default behavior of the configure/build process.

**Comment by rlfontenot** [comment]
This issue ties to  issue #20 .

**Comment by TimothyEDawson** [comment]
Minor note: Config options use hyphens, not underscores. So make sure it's --no-sub-dir
