### ISSUE TITLE
FAD limiter behavior

### ISSUE THREAD

**Issue by EdwardALuke** [EdwardALuke/loci#40]
Stable FAD derivatives need to disable passing FAD derivatives through the non-differentiable limiter functions.  This implements this 
in a straightforward way by using the realToDouble function in the final step.  In the longer run it would probably make sense to just doe these computations using doubles rather than carrying the FAD operations through the calculation only to discard at the end, but this is a nice clean approach that works for all FAD types.  This work is needed as part of delivery of the new FAD version of CHEM.

**Comment by TimothyEDawson** [comment]
Closed by #41.
