### ISSUE TITLE
Loci files translation confusion

### ISSUE THREAD

**Issue by EdwardALuke** [EdwardALuke/loci#8]
Loci files are translated to c++ files as part of the compilation process.  These c++ files can become confused with primary source files which can create problems when interacting with the version control system.  This issue is resolved by using the .lcc~ suffix to uniquely identify Loci intermediate files.  The trailing ~ is used so that these files will appear to be emacs save files which are already removed as part of the distclean targets in Loci makefiles.  Note that this requires that the compiler is explicitly told that the file that it is compiling is a c++ file, currently this has been done for the gcc compiler.  The llvm and intel compiler config files will need to be updated as a follow on issue.

**Comment by TimothyEDawson** [comment]
I noticed that the Makefiles for Tutorial/heat, quickTest/FVM, and src/FVMtools/geomTools still make the assumption that the lpp intermediate suffix is .cc. Should be a quick fix, I'll open up an issue if you don't get around to it before I do.

**Comment by EdwardALuke** [comment]
Ok
